name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Lint
      run: GO111MODULES=off go get github.com/golangci/golangci-lint && go install github.com/golangci/golangci-lint && golangci-lint run

    - name: Build
      run: go build -v ./

    - name: Test
      run: go test -v ./
